[package]
name = "pseudocode"
version = "0.1.0"
authors = ["aleph"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peeking_take_while = "0.1.2"
